version: '3.7'
services:
        vsftpd:
                image: pablokbs/panubo-vsftpd-arm
                environment:
                        - FTP_USER=admin
                        - FTP_PASSWORD=admin
                volumes:
                        - /home/pi/Documents:/srv
                expose:
                        - 21
                network_mode: host
